services:
  - type: web
    name: clinic-management-api
    env: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: clinic-management-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: clinic-management-db
    plan: free
    databaseName: clinic_management
    user: clinic_user
